import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import AppWalletProvider from "@/components/AppWalletProvider";
import { NavBar } from "@/components/Navbar";
import RedirectProvider from "@/components/RedirectProvider";

import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.className} min-h-screen overflow-x-hidden scroll-auto bg-gray-50 selection:bg-purple-100 selection:text-purple-600 antialiased dark:bg-gray-950 dark:text-white`}
    >
      <body>
        <Theme appearance="dark">
          <AppWalletProvider>
            <RedirectProvider>
              <NavBar />
              {children}
            </RedirectProvider>
          </AppWalletProvider>
        </Theme>
      </body>
    </html>
  );
}
