[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
program = "2ih4sUEu3vgBd236fG1qC1tEknLHGocahPF9yxnNW6FS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
